service:
  name: cloud-assignment

frameworkVersion: ">=2.0.0"

custom:
  defaultStage: dev
  defaultRegion: us-east-1

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, self:custom.defaultStage}
  region: ${opt:region, self:custom.defaultRegion}
  stackName: cloud-assignment-stack
  timeout: 120

package:
  include:
    - ./bin/handler
  exclude:
    - ./*.go
    - ./*.yml
    - ./go.mod
    - ./go.sum
    - ./.github/**
    - ./*.md
    - ./.gitignore

functions:
  replaceOrganisation:
    handler: bin/handler
    events:
      - http:
          method: POST
          path: /replaceOrganisation
          cors: true
